name: "test"
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: list
        id: set-matrix
        run: |
          from __future__ import print_function
          import json
          perl = [
              '5.32',
              '5.30',
              '5.28',
              '5.26',
              '5.24',
              '5.22',
              '5.20',
              '5.18',
              '5.16',
              '5.14',
              '5.12',
              '5.10'
          ]
          redis = [
              '6.2',
              '6.0',
              '5.0',
              '4.0',
              '3.2',
              '3.0',
              '2.8',
          ]
          backend = [
              'Redis',
              'Redis::Fast',
          ]
          includes = []
          for r in redis:
              for b in backend:
                  includes.append({
                      'perl': perl[0],
                      'redis': r,
                      'os': 'macos-latest',
                      'backend': b,
                  })

          matrix = {
              'perl': perl,
              'redis': redis,
              'os': ['ubuntu-latest'],
              'backend': backend,
              'include': includes
          }
          output = json.dumps(matrix, separators=(',', ':'))
          print('::set-output name=matrix::{0}'.format(output))
        shell: python

  test:
    runs-on: ${{ matrix.os }}
    needs: list

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.list.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Set up Redis ${{ matrix.redis }}
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis }}
          auto-start: false

      - name: Cache CPAN modules
        uses: actions/cache@v2
        with:
          path: |
            local
          key: ${{ runner.os }}-perl-${{ matrix.perl }}-${{ hashFiles('**/cpanfile') }}
          restore-keys: |
            ${{ runner.os }}-perl-${{ matrix.perl }}-${{ hashFiles('**/cpanfile') }}
            ${{ runner.os }}-perl-${{ matrix.perl }}-

      - name: Install
        run: |
          cpm install -L local --show-build-log-on-failure Minilla Redis Redis::Fast
          cpm install -L local --show-build-log-on-failure --with-develop
          echo "PERL5LIB=$(pwd)/local/lib/perl5" >> "$GITHUB_ENV"
          echo "$(pwd)/local/bin" >> "$GITHUB_PATH"

      - name: Test
        run: |
          minil test
        env:
          REDIS_BACKEND: ${{ matrix.backend }}
